<style type="text/css">

    .entry-edit .entry-edit-head { background:#0383cc !important; }
    .content-header { margin-bottom: 0px !important; }

</style>
<div style="overflow: hidden;"><img src="<?php echo $this->getSkinUrl('images/smsapi/sms/smsapi_logo.jpg'); ?>"></div>
<div class="comment"><?php echo Mage::helper('sms')->__('SMSAPI Module for Magento-based stores enables automatic send SMS notifications to customers. SMS communication has many benefits including facilitates communication with your customers and speeds up reaching the details of the order. Short text messages are sent primarily as information on the status of the order, such as a message confirming the correct course of a transaction or message about delivery time of orders. SMS is fastest communication with your customers, and savings for the company due to reduced costs associated with undelivered shipments. SMS notifications in Magento module can be sent from the field in active sender SMSAPI account. Content templates are fully editable.'); ?></div>